Insert into Journey_Audience_Definition ("Name", "Frequency", "Recency", "SegmentName", "PixelId", "Active", "AccountId", "URLMask", "AudienceType") values('Test Audience1',3, 10, 'Segment1', 1235, 1, 559145, 'Test URL Mask', 1);
Insert into Journey_Audience_Conditions ("AudienceId", "ConditionTypeId", "Operator", "ConditionValue", "Active") values (1, 1, 1, 'test', 1);
Insert into Journey_Audience_Conditions ("AudienceId", "ConditionTypeId", "Operator", "ConditionValue", "Active") values (1, 1, 1, 'test2', 1);
Insert into Journey_Audience_Definition ("Name", "Frequency", "Recency", "SegmentName", "PixelId", "Active", "AccountId", "URLMask", "AudienceType") values('Test Audience2',3, 10, 'Segment1', 1235, 1, 559145, 'Test URL Mask', 1);
Insert into Journey_Audience_Conditions ("AudienceId", "ConditionTypeId", "Operator", "ConditionValue", "Active") values (2, 1, 1, 'test2', 1);
Insert into Journey_Audience_Definition ("Name", "Frequency", "Recency", "SegmentName", "PixelId", "Active", "AccountId", "URLMask", "AudienceType") values('Test Audience3',3, 10, 'Segment1', 1235, 1, 559145, 'Test URL Mask', 1);
Insert into Journey_Audience_Conditions ("AudienceId", "ConditionTypeId", "Operator", "ConditionValue", "Active") values (3, 1, 1, 'test3', 1);
Insert into Journey_Audience_Definition ("Name", "Frequency", "Recency", "SegmentName", "PixelId", "Active", "AccountId", "URLMask", "AudienceType") values('Test Audience4',3, 10, 'Segment1', 1235, 1, 559145, 'Test URL Mask', 1);
Insert into Journey_Audience_Conditions ("AudienceId", "ConditionTypeId", "Operator", "ConditionValue", "Active") values (4, 1, 1, 'test4', 1);
Insert into Journey_Audience_Definition ("Name", "Frequency", "Recency", "SegmentName", "PixelId", "Active", "AccountId", "URLMask", "AudienceType") values('Test Audience5',3, 10, 'Segment1', 1235, 1, 559145, 'Test URL Mask', 1);
Insert into Journey_Audience_Conditions ("AudienceId", "ConditionTypeId", "Operator", "ConditionValue", "Active") values (5, 1, 1, 'test5', 1);
Insert into Journey_Audience_Definition ("Name", "Frequency", "Recency", "SegmentName", "PixelId", "Active", "AccountId", "URLMask", "AudienceType") values('Test Audience6',3, 10, 'Segment1', 1235, 1, 559145, 'Test URL Mask', 1);
Insert into Journey_Audience_Conditions ("AudienceId", "ConditionTypeId", "Operator", "ConditionValue", "Active") values (6, 1, 1, 'test6', 1);
Insert into Journey_Audience_Definition ("Name", "Frequency", "Recency", "SegmentName", "PixelId", "Active", "AccountId", "URLMask", "AudienceType") values('Test Audience7',3, 10, 'Segment1', 1235, 1, 559145, 'Test URL Mask', 1);
Insert into Journey_Audience_Conditions ("AudienceId", "ConditionTypeId", "Operator", "ConditionValue", "Active") values (7, 1, 1, 'test7', 1);
Insert into Journey_Audience_Definition ("Name", "Frequency", "Recency", "SegmentName", "PixelId", "Active", "AccountId", "URLMask", "AudienceType") values('Test Audience8',3, 10, 'Segment1', 1235, 1, 559145, 'Test URL Mask', 1);
Insert into Journey_Audience_Conditions ("AudienceId", "ConditionTypeId", "Operator", "ConditionValue", "Active") values (8, 1, 1, 'test8', 1);
Insert into Journey_Audience_Definition ("Name", "Frequency", "Recency", "SegmentName", "PixelId", "Active", "AccountId", "URLMask", "AudienceType") values('Test Audience9',3, 10, 'Segment1', 1235, 1, 559145, 'Test URL Mask', 1);
Insert into Journey_Audience_Conditions ("AudienceId", "ConditionTypeId", "Operator", "ConditionValue", "Active") values (9, 1, 1, 'test9', 1);
Insert into Journey_Audience_Definition ("Name", "Frequency", "Recency", "SegmentName", "PixelId", "Active", "AccountId", "URLMask", "AudienceType") values('Test Audience10',3, 10, 'Segment1', 1235, 1, 559145, 'Test URL Mask', 1);
Insert into Journey_Audience_Conditions ("AudienceId", "ConditionTypeId", "Operator", "ConditionValue", "Active") values (10, 1, 1, 'test10', 1);
Insert into Journey_Audience_Definition ("Name", "Frequency", "Recency", "SegmentName", "PixelId", "Active", "AccountId", "URLMask", "AudienceType") values('Test Audience11',3, 10, 'Segment1', 1235, 1, 559145, 'Test URL Mask', 1);
Insert into Journey_Audience_Conditions ("AudienceId", "ConditionTypeId", "Operator", "ConditionValue", "Active") values (11, 1, 1, 'test11', 1);
Insert into Journey_Audience_Definition ("Name", "Frequency", "Recency", "SegmentName", "PixelId", "Active", "AccountId", "URLMask", "AudienceType") values('Test Audience12',3, 10, 'Segment1', 1235, 1, 559145, 'Test URL Mask', 1);
Insert into Journey_Audience_Conditions ("AudienceId", "ConditionTypeId", "Operator", "ConditionValue", "Active") values (12, 1, 1, 'test12', 1);
Insert into Journey_Audience_Definition ("Name", "Frequency", "Recency", "SegmentName", "PixelId", "Active", "AccountId", "URLMask", "AudienceType") values('Test Audience13',3, 10, 'Segment1', 1235, 0, 559145, 'Test URL Mask', 1);
Insert into Journey_Audience_Recording_Pixel_Xref ("AudienceId", "PixelId", "Active") values (1, 1, 1);
Insert into Journey_Audience_Recording_Pixel_Xref ("AudienceId", "PixelId", "Active") values (1, 2, 1);